# Generated by Django 2.2.1 on 2019-05-23 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=200)),
                ('partOfSpeech', models.CharField(choices=[('n', 'Noun'), ('a', 'Adjective'), ('v', 'Verb'), ('s', 'Sentence')], max_length=1)),
            ],
        ),
    ]
