# Generated by Django 2.2.1 on 2019-05-26 22:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spew', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NameGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='word',
            name='partOfSpeech',
            field=models.CharField(choices=[('no', 'Noun'), ('ad', 'Adjective'), ('na', 'Name'), ('se', 'Sentence'), ('av', 'Adverb'), ('s?', 'Interrogative'), ('pn', 'Plural Noun')], max_length=2),
        ),
        migrations.AddField(
            model_name='word',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='spew.NameGroup'),
        ),
    ]
