# Generated by Django 2.2.1 on 2019-05-29 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spew', '0002_auto_20190526_1839'),
    ]

    operations = [
        migrations.CreateModel(
            name='LastSentence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sentence', models.TextField()),
                ('time', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
