# Generated by Django 2.2.1 on 2019-05-30 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spew', '0004_lastsentence_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='partOfSpeech',
            field=models.CharField(choices=[('no', 'Noun'), ('ad', 'Adjective'), ('na', 'Name'), ('se', 'Sentence'), ('av', 'Adverb'), ('s?', 'Interrogative'), ('pn', 'Plural Noun'), ('su', 'Suggestion')], max_length=2),
        ),
    ]
